# Based on https://github.com/geerlingguy/ansible-role-kubernetes/blob/master/tasks/setup-RedHat.yml

- name: Set up Kubernetes on EL7
  hosts: "{{ hosts }}"
  tasks:

  - name: Ensure Kubernetes repository exists.
    yum_repository:
      name: kubernetes
      description: Kubernetes
      enabled: true
      gpgcheck: true
      repo_gpgcheck: true
      baseurl: "{{ kubernetes_yum_base_url }}"
      gpgkey: "{{ kubernetes_yum_gpg_key }}"
  
  - name: Add Kubernetes GPG keys.
    rpm_key:
      key: "{{ item }}"
      state: present
      validate_certs: no
    register: kubernetes_rpm_key
    with_items: "{{ kubernetes_yum_gpg_key }}"
  
  - name: Make cache if Kubernetes GPG key changed.
    command: "yum -q makecache -y --disablerepo='*' --enablerepo='kubernetes' {{ no_check_option }}"
    when: kubernetes_rpm_key is changed
    args:
      warn: false

  become: true

  vars:
    kubernetes_yum_arch: '$basearch'
    kubernetes_yum_base_url: "https://packages.cloud.google.com/yum/repos/kubernetes-el7-{{ kubernetes_yum_arch }}"
    kubernetes_yum_gpg_key:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

    no_check_option: "{{ '--nogpgcheck' if no_check | default(false) == true else '' }}"
