- name: Redhat repo fun
  hosts: "{{ hosts }}"
  tasks:

  - block:
    - name: Look for disabled repos that may need to be enabled
      shell: "{{ ansible_pkg_mgr }} repolist disabled | grep -E 'rhui-optional-rpms|codeready-builder-for-rhel-.*rhui-rpms'"
      register: disabled_repos
      failed_when: false
    
    - name: Enable disabled repos that may be needed
      command: "yum-config-manager --enable {{ item }}"
      loop: "{{ disabled_repos.stdout | regex_findall('^([^ /]*)', multiline=True) }}"
      become: true
      when: disabled_repos.stdout != ''

    when:
      ansible_pkg_mgr in ['yum', 'dnf']
