- name: Working out steps to update /etc/fstab
  hosts: "{{ hosts|default('localhost') }}"
  tasks:

  - name: Find current mount point for /tmp via /etc/fstab
    command: awk '($0 !~ "^#") { if ($2 == "/tmp") print $2 "," $1 "," $3 }' /etc/fstab
    args:
      warn: false
    changed_when: false
    register: tmp_fstab_results

  - name: Find current mount point for /tmp via mount
    shell: mount | awk -F ' ' '($3 == "/tmp") {print $3 "," $1 "," $5}'
    args:
      warn: false
    changed_when: false
    register: tmp_mount_results

  - name: Determine mount information
    set_fact:
      tmp_mount: "{{ (tmp_fstab_results.stdout_lines|default('')) | ternary(tmp_fstab_results.stdout_lines, tmp_mount_results.stdout_lines|default('')) }}"

  - name: Dump
    debug:
      var: tmp_mount
