- name: Working out steps to update /etc/fstab
  hosts: "{{ hosts|default('localhost') }}"
  tasks:

  - name: Find current mount point for /tmp via /etc/fstab
    command: awk '($0 !~ "^#") { if ($2 == "/tmp") print $2 "," $1 "," $3 }' /etc/fstab
    args:
      warn: false
    changed_when: false
    register: fstab_mount_results

  - name: Find current mount point for /tmp via mount
    shell: mount | awk -F ' ' '($3 == "/tmp") {print $3 "," $1 "," $5}'
    args:
      warn: false
    changed_when: false
    register: mount_mount_results

  - name: Dump mount_results
    debug:
      msg: "{{ fstab_mount_results.stdout if fstab_mount_results.stdout|default('')!='' else mount_mount_results.stdout|default('') }}"
