- name: Play with home directory
  hosts: "{{ hosts | default('localhost') }}"
  tasks:
  - name: Get home directory
    shell: "echo $HOME"
    register: home_directory

  - name: Set home variable
    set_fact:
      home: "{{ home_directory.stdout_lines[0] }}"

  - name: Display
    debug:
      var: home
