# inspired by https://dev.to/setevoy/ansible-check-if-a-package-installed-on-a-remote-system-4402

- name: Check to see if a package is installed
  hosts: "{{ hosts | default('localhost') }}"
  tasks:

  - name: Gather the packager facts
    package_facts:

  - name: Package status
    debug: 
      msg: "{{ inventory_hostname }}: {{ item }} {{ 'installed' if item in ansible_facts.packages else 'not installed' }}"
    loop: "{{ pkgs | default([]) }}"
