# cd ~
# mkdir .kube
# sudo cp /etc/kubernetes/admin.conf .kube/config
# sudo chmod 644 .kube/config
# kubectl get nodes

- name: "Perform 'kubectl get nodes'"
  hosts: "{{ hosts | default('master0') }}"
  tasks:

  - name: "Set `dir` variable"
    set_fact:
      home: "{{ lookup('env', 'HOME') }}"

  - name: Ensure ~/.kube exists
    file:
      path: "{{ home }}/.kube"
      state: directory

  - name: Copy admin.conf
    copy:
      remote_src: true
      src: /etc/kubernetes/admin.conf
      dest: "{{ home }}/.kube/config"
      mode: "0644"
      user: "{{ ansible_user }}"
    become: true

  - name: kubectl
    command: kubectl get nodes
    register: kubectl

  - name: Output
    debug:
      var: kubectl.stdout_lines
