- name: Test logic inside a loop variable
  hosts: localhost
  tasks:
  - debug:
      var: item
    loop:
      - ["OnAccessPrevention {{ 'yes' if setup_clamav_clamonacc_scanning == true else 'no' }}", '^OnAccessPrevention\s+']
      # - ["OnAccessPrevention " setup_clamav_clamonacc_scanning, '^OnAccessPrevention\s+']
      - ["OnAccessExcludeUname {{ clamav_clam_user }}", '^OnAccessExcludeUname\s+']
  vars:
    setup_clamav_clamonacc_scanning: true
    clamav_clam_user: root
