- name: Play with `replace` and `lineinfile`
  hosts: localhost
  gather_facts: false
  tasks:

  - name: Remove files
    file:
      path: "{{ item }}"
      state: absent
    loop:
      - replace_file
      - lineinfile_file
    when: remove_files | default(false) == true

  - name: Create files
    shell: "echo TEST > {{ item }}"
    loop:
      - replace_file
      - lineinfile_file
    when: create_files | default(true) == true

  - name: Use replace
    replace:
      dest: replace_file
      regexp: "test"
      replace: "this is a test"
    when: do_replace | default(true) == true

  - name: Use lineinfile
    lineinfile:
      dest: lineinfile_file
      regexp: "test"
      line: "this is a test"
    when: do_lineinfile | default(true) == true
