# not defined: ansible-playbook undef.yaml
# defined: ansible-playbook -e var=foo undef.yaml

- name: Work with undefined variables
  hosts: localhost
  gather_facts: false
  tasks:

  - name: Is it defined?
    debug:
      msg: "{{ 'var is ' + var if var is defined else 'var is not defined' }}"

  - name: Provide a default
    debug:
      msg: "{{ 'value is ' + var | default('?') }}"
