- name: Locate package a command is from
  hosts: "{{ hosts | default('localhost') }}"
  tasks:
    - name: Process a command
      include_tasks: where-command-tasks.yml
      loop: "{{ commands }}"

  vars:
    locate_command: "{{ 'apt-file search' if ansible_os_family == 'Debian' else 'rpm -q --whatprovides' }}"
