- name: Check if an executable is in the PATH
  hosts: "{{ hosts | default('localhost') }}"
  tasks:
  - name: Perform which
    command: "which {{ target }}"
    failed_when: false
    register: which_task

  - name: Act on which result
    debug:
      msg: "{{ target }} is {{ 'found' if which_task.rc == 0 else 'not found' }}"
