- name: Try custom module
  hosts: all
  become: true
  tasks:
  - name: Run custom module
    my_module:
      command: id
    # become: yes
    # become_user: root
    # become_method: sudo
    register: output
    delegate_to: localhost

  - debug:
      var: output
